version: "3.8"
services:
  database:
    image: postgres:alpine
    container_name: dev-postgres-demacia
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ds_demacia
    ports:
      - 5433:5433
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: